version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /apps/nodes_modules
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /apps/nodes_modules
      - .:/app
    command: ["npm", "run", "test"]